### ISSUE TITLE
无法在ButterKnife.bind 下面生成 findviewbyid 代码

### ISSUE THREAD

**Issue by liukewill** [u3shadow/RemoveButterKnife#13]
as  v2.3.2    removebutterknife v1.2.0
只是去掉了  注解代码，没有生成findviewbyid代码
是我打开方式不对吗？

**Comment by liukewill** [comment]
问题解决了
看了生成code的源码 是分割字符串导致的
`String viewName = returnValue.trim().split(" ")[1]+".";
老铁这段代码写的稍微有点硬

我的contentview的声明是在BaseFragment中的，分割字符串没取到viewname
所以没生成代码。
done。

**Comment by MaYunFei** [comment]
确实是硬，谢谢

**Comment by u3shadow** [comment]
我可是条硬汉(笑
