### ISSUE TITLE
不起作用

### ISSUE THREAD

**Issue by Roger110** [u3shadow/RemoveButterKnife#14]
最新的as 3.1.2运行这个插件无效，能否升级一下

**Comment by u3shadow** [comment]
好的，收到了，近期就会修改

**Comment by u3shadow** [comment]
@Roger110 你好，能提供一下无效的代码文件吗，我这边测试的情况3.1.2是可以正常工作的

**Comment by Roger110** [comment]
是module里面R2造成的，先把R2改为R就是好的，这个可以优化下
