### ISSUE TITLE
Need modification

### ISSUE THREAD

**Issue by MS893** [u3shadow/RemoveButterKnife#15]
Thank you for the plugin, it helps me . I have noticed just one problem.

**_Applying the plugin on this code :_**

public class StockUpdateViewHolder extends RecyclerView.ViewHolder {
@BindView(R.id.stock_item_symbol)
TextView stockSymbol;

StockUpdateViewHolder(View v) {
    super(v);
    ButterKnife.bind(this, v);
}

**_Makes that :_**

public class StockUpdateViewHolder extends RecyclerView.ViewHolder {
TextView stockSymbol;

StockUpdateViewHolder(View v) {
    super(v);
}

**_Instead of :_**

public class StockUpdateViewHolder extends RecyclerView.ViewHolder {
TextView stockSymbol;

StockUpdateViewHolder(View v) {
    super(v);
    stockSymbol = v.findViewById(R.id.stock_item_symbol);
}

**Comment by u3shadow** [comment]
@MS893 
Thank you for use it
I'm already working on it.
You can find the progress here https://github.com/u3shadow/RemoveButterKnife/projects/1
Hope you have a nice day!

**Comment by MS893** [comment]
Yes! Thank you... +++++++++

**Comment by MS893** [comment]
Thank you my friend.
Best regards
Christian
