### ISSUE TITLE
不支持自定义view里面移除.

### ISSUE THREAD

**Issue by vicwing** [u3shadow/RemoveButterKnife#5]
在Activity和fragment里面可以使用,但是自定义的view里面只能移除注解,不能自动生成findviewbyid.的代码

**Comment by u3shadow** [comment]
因为自定义view里面无法定位什么时候加载了layout

**Comment by vicwing** [comment]
原来这样.谢谢.

**Comment by u3shadow** [comment]
：）

**Comment by u3shadow** [comment]
@vicwing 已支持在组合自定义view中的删除和生成操作
