### ISSUE TITLE
[Improvement] 支持ButterKnife的@OnClick注解

### ISSUE THREAD

**Issue by xieyiyi** [u3shadow/RemoveButterKnife#7]
RT
能移除findViewById挺不错，能移除ButterKnife提供的其它注解就更好了
如@OnClick、@BindInt等

**Comment by u3shadow** [comment]
移除了onclick会让代码无法运行，因为可能没有对应的view实例来设置点击回调方法，所以没有添加

XieYi <notifications@github.com>于2016年9月5日星期一 14:35写道：

**Comment by xieyiyi** [comment]
嗯，自动生成onClick相关的代码会麻烦一些
