### ISSUE TITLE
在Android Studio 1.4和Android 2.1上均运行不正常

### ISSUE THREAD

**Issue by xieyiyi** [u3shadow/RemoveButterKnife#8]
原因未知
ButterKnife 7的 @Bind(R.id.xxx) 和 8的 @BindView(R.id.xxx) 这样的语法均不支持

**Comment by u3shadow** [comment]
是不是没有分行，把bind和实例化写在一行，无法识别这种情况的

XieYi <notifications@github.com>于2016年9月5日星期一 20:06写道：

**Comment by xieyiyi** [comment]
@u3shadow 呃，这个不支持的话很奇怪啊，写在一行还是两行属于代码风格的范畴，类似于花括号开口在行尾还是在新开一行的行首，不应该因为这个影响到功能

**Comment by u3shadow** [comment]
这个跟查询方式有关，后面会针对这个做调整，谢谢你的反馈

XieYi <notifications@github.com>于2016年9月5日星期一 20:51写道：

**Comment by xieyiyi** [comment]
@u3shadow 嗯嗯，还有个小小的建议，View的强制转换加了之后有个Intellij的提示说没有必要强制转换，可以省略

**Comment by u3shadow** [comment]
关于那个提示有截图能看看吗，我这边没有出现呢

**Comment by xieyiyi** [comment]
其实很简单，就是强制类型转换时出现的，比如
Double i = 2;
Double j = (Double) i;
这时候IDE肯定会提示你不必要进行强制类型转换的。

**Comment by u3shadow** [comment]
是的，但是我这里没有出现这个提示啊，而且findviewbyid前面的标准写法也是要加强制转换的吧

**Comment by u3shadow** [comment]
单行写法问题已经在最新提交中修复
